{{- if .Values.pihole.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pi-hole.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pi-hole.name" . }}
    helm.sh/chart: {{ include "pi-hole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.pihole.password | b64enc }}
{{- end }}