global:

  # The main enabled/disabled setting. If true, servers, clients, Consul DNS and the
  # Consul UI will be enabled. Each component can override this default via its
  #component-specific "enabled" config. If false, no components will be installed by
  #default and per-component opt-in is required, such as by setting server.enabled to
  #true.
  enabled: true

  # Set the prefix used for all resources in the Helm chart. If not set,
  # the prefix will be `<helm release name>-consul`.
  # @type: string
  name: vc

  # The name of the datacenter that the agents should
  # register as. This can't be changed once the Consul cluster is up and running
  # since Consul doesn't support an automatic way to change this value currently:
  datacenter: vault-k8s

client:
  enabled: true

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
  storage: 10Gi
  storageClass: vault-storage
