server:
  ha:
    enabled: true

    config: |
      ui = true
      replicas: 1

      listener "tcp" {
        tls_disable = true
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

    resources:
      requests: 
        memory: '1Gi'
      limits:
        memory: '1Gi'

    config: |
      ui = true

      listener "tcp" {
        tls_disable = true
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "vault.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: vault-storage
    accessMode: ReadWriteOnce

  auditStorage:
    enabled:  false
    size: 10Gi
    storageClass: vault-storage
    accessMode: ReadWriteOnce
ui:
  enabled:  true
  serviceType:  LoadBalancer
  annotations: {
    metallb.universe.tf/address-pool: address-pool-1
  }

