global:

  # The main enabled/disabled setting. If true, servers, clients, Consul DNS and the
  # Consul UI will be enabled. Each component can override this default via its
  #component-specific "enabled" config. If false, no components will be installed by
  #default and per-component opt-in is required, such as by setting server.enabled to
  #true.
  enabled: true

  # Set the prefix used for all resources in the Helm chart. If not set,
  # the prefix will be `<helm release name>-consul`.
  # @type: string
  name: consul

  # The name of the datacenter that the agents should
  # register as. This can't be changed once the Consul cluster is up and running
  # since Consul doesn't support an automatic way to change this value currently:
  datacenter: home
  
  # The name (and tag) of the Consul Docker image for clients and servers. This can be 
  # overridden per component. This should be pinned to a specific version tag, otherwise you may 
  # inadvertently upgrade your Consul version.
  image: "hashicorp/consul-enterprise:1.8-ent"

  # gossipEncryption - Configures which Kubernetes secret to retrieve Consul's gossip encryption key 
  # from (see -encrypt (https://consul.io/docs/agent/options#_encrypt)). If secretName or secretKey are not set, 
  # gossip encryption will not be enabled. The secret must be in the same namespace that Consul is installed into.

  # The secret can be created by running:
  # $ kubectl create secret generic consul-gossip-encryption-key --from-literal=key=$(consul keygen)


client:
  enabled: true

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
  storage: 10Gi
  storageClass: consul-storage
  nodeSelector: |
    beta.kubernetes.io/arch: amd64
  
ui:
  service:
    type: LoadBalancer
    annotations: |
      metallb.universe.tf/address-pool: address-pool-1

connectInject:
  enabled: true

controller:
  enabled: true